# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HWmV3ftueF77RxHn6SmHj-zRLFXRO8aR
"""

# Cell 1: Install required packages
!pip install -q pypdf langchain langchain-community langchain-huggingface sentence-transformers chromadb nltk spacy google-genai
!python -m spacy download en_core_web_sm -q

# Cell 2: NLP Preprocessing & Cleaning Pipeline (Updated Downloads)
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
import spacy

# تحميل الموارد المطلوبة من NLTK بما فيها punkt_tab
nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)
nltk.download('stopwords', quiet=True)
nltk.download('wordnet', quiet=True)
nltk.download('omw-1.4', quiet=True)

nlp = spacy.load("en_core_web_sm")
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def clean_and_preprocess(raw_text):
    print("--- Original Text ---")
    print(raw_text)

    # 1. Lowercasing
    text = raw_text.lower()

    # 2. Remove HTML Tags & URLs
    text = re.sub(r'<.*?>', '', text)
    text = re.sub(r'https?://\S+|www\.\S+', '', text)

    # 3. Remove Punctuation & Special Characters / Numbers
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()

    # 4. Tokenization (Word-level)
    tokens = nltk.word_tokenize(text)

    # 5. Stopwords Removal
    filtered_tokens = [w for w in tokens if w not in stop_words]

    # 6. Stemming vs. Lemmatization
    stemmed = [stemmer.stem(w) for w in filtered_tokens]
    lemmatized = [lemmatizer.lemmatize(w) for w in filtered_tokens]

    return {
        "cleaned_tokens": filtered_tokens,
        "stemmed": stemmed,
        "lemmatized": lemmatized
    }

# تجربة دالة التنظيف
sample_doc = "<h1>Natural Language Processing!</h1> Visit https://example.com for 100+ NLP guides & caring models."
result = clean_and_preprocess(sample_doc)
print("\n--- Cleaned & Processed ---")
print("Lemmatized Tokens:", result['lemmatized'])
print("Stemmed Tokens:   ", result['stemmed'])

# Cell 3: Padding & Truncation (Token Sequences)
def pad_or_truncate(tokens, max_len=7, pad_token="<PAD>"):
    if len(tokens) > max_len:
        # Truncation
        return tokens[:max_len]
    else:
        # Padding
        return tokens + [pad_token] * (max_len - len(tokens))

print("Original Tokens:", result['lemmatized'])
padded_seq = pad_or_truncate(result['lemmatized'], max_len=7)
print("Padded/Truncated Sequence (Fixed Len = 7):", padded_seq)

# Cell 4: PDF Loading & Chunking (Updated Imports & Direct Text Fallback)
import os
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.documents import Document

pdf_path = "NLP - Text preprocessing.pdf"

# فحص ما إذا كان الملف موجوداً على Colab
if os.path.exists(pdf_path):
    loader = PyPDFLoader(pdf_path)
    documents = loader.load()
    print(f"Loaded {len(documents)} pages from uploaded PDF.")
else:
    print(f"Notice: '{pdf_path}' not found in runtime. Using slide content directly.")
    documents = [
        Document(page_content="Natural Language Processing (NLP) is a field within artificial intelligence (AI) and computational linguistics focusing on interactions between computers and human language."),
        Document(page_content="Natural Language Understanding (NLU) focuses on comprehension, intent, and semantics. Natural Language Generation (NLG) creates coherent text from structured data."),
        Document(page_content="Text preprocessing steps include Lowercasing, Tokenization, Stopwords removal, Stemming, Lemmatization, POS tagging, and NER."),
        Document(page_content="Stemming removes word suffixes fast but may not return real words. Lemmatization uses lexical vocabulary and returns valid dictionary root words."),
        Document(page_content="Padding adds special tokens to equalize sequence length, while truncation cuts tokens exceeding maximum allowed length.")
    ]

# تقسيم المستند إلى Chunks
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=300,
    chunk_overlap=50
)

chunks = text_splitter.split_documents(documents)
print(f"Total Chunks created: {len(chunks)}")
print("\nFirst Chunk Preview:\n", chunks[0].page_content)

# Cell 5: Embeddings & Vector Store (ChromaDB)
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma

# استخدام نموذج Pretrained خفيف وسريع للـ Embeddings
embedding_model = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

# إنشاء الـ Vector Database وتخزين الـ Chunks فيها
vector_db = Chroma.from_documents(
    documents=chunks,
    embedding=embedding_model,
    collection_name="nlp_preprocessing_rag"
)

print("Vector Database created and indexed successfully!")

# Cell 6: User Query & Vector Search with Similarity Scores
user_query = "What is the difference between stemming and lemmatization?"

# استرجاع أكثر النصوص تطابقاً مع إظهار درجات التشابه (Similarity / Distance)
results_with_scores = vector_db.similarity_search_with_relevance_scores(user_query, k=3)

print(f"--- Query: '{user_query}' ---\n")
retrieved_context = []
for doc, score in results_with_scores:
    print(f"[Score: {score:.4f}] Chunk:")
    print(doc.page_content)
    print("-" * 50)
    retrieved_context.append(doc.page_content)

# تجميع السياق المسترجع في نص واحد
context_block = "\n\n".join(retrieved_context)

# Cell 7: Generation using LLM & Custom Prompt
from google import genai
import os

# تجهيز الـ Prompt المدمج بالسياق المسترجع والسؤال
prompt = f"""You are an AI assistant. Answer the user's question based strictly on the provided context.

### Context:
{context_block}

### Question:
{user_query}

### Answer:"""

print("--- Final Formatted Prompt ---\n")
print(prompt)
print("\n" + "=" * 50 + "\n")

# Put your API key directly here
api_key = "AQ.Ab8RN6Jifjn1SQ_O9Ifk2zPIJV1II7P0-7NQ-3Kxco70Qs-FzQ"

if api_key:
    client = genai.Client(api_key=api_key)
    response = client.models.generate_content(
        model="gemini-3.6-flash",
        contents=prompt,
    )
    print("--- Generated Response ---")
    print(response.text)
else:
    print("Add your GEMINI_API_KEY to run the LLM generation step.")

# Interactive RAG Chatbot Loop
import os
from google import genai

# الـ API Key الخاص بكِ
api_key = "AQ.Ab8RN6Jifjn1SQ_O9Ifk2zPIJV1II7P0-7NQ-3Kxco70Qs-FzQ"


def ask_pdf_bot(question, vector_database, k_chunks=3):
    # 1. Similarity Retrieval
    # استخدام similarity_search العادية لتجنب تحذيرات الـ relevance scores السلبية
    results = vector_database.similarity_search(question, k=k_chunks)

    context_chunks = [doc.page_content for doc in results]
    context = "\n\n".join(context_chunks)

    # 2. Prompt Engineering
    prompt = f"""You are a helpful NLP expert assistant.
Answer the user question using ONLY the provided context below. If the answer is not contained within the context, politely state that you cannot find the answer in the document.

Context:
{context}

Question:
{question}

Answer:"""

    # 3. LLM Generation
    try:
        client = genai.Client(api_key=api_key)
        response = client.models.generate_content(
            model="gemini-3.6-flash", contents=prompt  # تم التعديل إلى 3.6
        )
        return response.text.strip()
    except Exception as e:
        return f"Error connecting to LLM: {e}"


# تشغيل الشات بوت بشكل تفاعلي
print("🤖 NLP PDF Chatbot is ready! (Type 'exit' or 'quit' to stop)\n" + "=" * 50)

while True:
    user_input = input("\n👤 You: ")
    if user_input.strip().lower() in ["exit", "quit", "q"]:
        print("\n👋 Chat ended. Good luck!")
        break

    if not user_input.strip():
        continue

    print("\n🔍 Searching & Generating answer...")
    answer = ask_pdf_bot(user_input, vector_db)
    print(f"\n🤖 Bot:\n{answer}\n")
    print("-" * 50)