# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lD--_W4X6BsLYAVTcmdVoc9N_OEITxd7
"""



# ============================================
# STEP 2: Load the model and tokenizer
# ============================================
from transformers import MarianMTModel, MarianTokenizer

model_name = "Helsinki-NLP/opus-mt-ar-en"

tokenizer = MarianTokenizer.from_pretrained(model_name)
model = MarianMTModel.from_pretrained(model_name)

print("Model loaded successfully!")


# ============================================
# STEP 3: Build the BATCH translation function
# ============================================
def translate(text_block):
    # Split input into separate sentences (one per line)
    sentences = [line.strip() for line in text_block.split("\n") if line.strip() != ""]

    if len(sentences) == 0:
        return "Please enter at least one sentence."

    # Tokenize all sentences together as a batch (padding=True is needed here)
    inputs = tokenizer(sentences, return_tensors="pt", padding=True, truncation=True)

    # Generate translations for the whole batch at once
    translated_tokens = model.generate(**inputs)

    # Decode each translated sentence
    translations = [
        tokenizer.decode(t, skip_special_tokens=True) for t in translated_tokens
    ]

    # Pair each original sentence with its translation
    result = "\n".join(
        f"{i+1}. {sentences[i]}  ->  {translations[i]}"
        for i in range(len(sentences))
    )

    return result
# ============================================
# STEP 4: Test the function with multiple sentences
# ============================================
sample_sentences = [
    "مرحبا كيف حالك اليوم",
    "الذكاء الاصطناعي يغير العالم بسرعة كبيرة",
    "انا بتعلم الترجمة الالية باستخدام بايثون"
]

sample_text = "\n".join(sample_sentences)

print(translate(sample_text))